[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = "ml_package_framework"

[tool.pylint.MASTER]
ignore-paths = [
    ".venv",
    "build",
    "dist"
]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "C0103",  # Variable name doesn't conform to snake_case naming style
    "C0114",  # Missing module docstring
    # Add other error codes here
]

[tool.mypy]
files = ["ml_package_framework", "tests"]
ignore_missing_imports = true
